services:
  db:
    image: postgres:14.19-alpine3.21
    restart: always
    environment:
      - POSTGRES_DB=workoutdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  workout-service:
    depends_on:
      - db
      - kafka
      - zookeeper
    build: workout-service/.
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://db:5432/workoutdb
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - JWT_SECRET=secretkey
      - JWT_EXPIRATON=86400000
      - KAFKA_HOST=kafka:9092
    
  notification-service:
    build: notification-service/.
    restart: always
    depends_on:
      - workout-service
      - kafka
      - zookeeper
    ports:
      - 8081:8081
    environment:
      - server.port=8081
      - KAFKA_HOST=kafka:9092
      - EMAIL=<Your email>
      - EMAIL_PASSWORD=<your password>
      - EMAIL_HOST=<your email host>
      - EMAIL_PORT=<your email host port>

  prometheus:
    depends_on:
      - workout-service
      - notification-service
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 22181:2181
  
  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    ports:
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  kafka-ui:
    depends_on:
      - kafka
      - zookeeper
    image: provectuslabs/kafka-ui:latest
    ports:
      - "3000:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:22181    